FROM node:16-alpine AS builder
WORKDIR /tmp
COPY ./frontend/package.json /tmp
COPY ./frontend/package-lock.json /tmp
COPY ./frontend/tsconfig.json /tmp
RUN npm ci
COPY ./frontend/public /tmp/public
COPY ./frontend/src /tmp/src
COPY ./frontend/.env /tmp
RUN npm run build

FROM nginx:1.19
COPY --from=builder /tmp/build/ /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
