FROM node:16-alpine
RUN mkdir -p /usr/src/server
WORKDIR /usr/src/server
COPY ./server/package.json /usr/src/server
COPY ./server/package-lock.json /usr/src/server
COPY ./server/tsconfig.json /usr/src/server
RUN npm ci
COPY ./server/src /usr/src/server/src
CMD ["npm", "start"]
